from http import HTTPStatus

OK = HTTPStatus.OK
FORBIDDEN = HTTPStatus.FORBIDDEN
INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
METHOD_NOT_ALLOWED = HTTPStatus.METHOD_NOT_ALLOWED
NOT_FOUND = HTTPStatus.NOT_FOUND
FOUND = HTTPStatus.FOUND
CREATED = HTTPStatus.CREATED
BAD_REQUEST = HTTPStatus.BAD_REQUEST
