"""changes

Revision ID: 0eeb91ac4329
Revises: f5891dcaa098
Create Date: 2023-10-12 19:15:11.142618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0eeb91ac4329"
down_revision = "f5891dcaa098"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("building", schema=None) as batch_op:
        batch_op.alter_column(
            "latitude",
            existing_type=sa.VARCHAR(),
            type_=sa.Float(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "longitude",
            existing_type=sa.VARCHAR(),
            type_=sa.Float(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("building", schema=None) as batch_op:
        batch_op.alter_column(
            "longitude",
            existing_type=sa.Float(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "latitude",
            existing_type=sa.Float(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
