"""first_migration

Revision ID: 258326e24a99
Revises: 
Create Date: 2023-10-14 00:15:08.095405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "258326e24a99"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.Column("latitude", sa.String(length=15), nullable=False),
        sa.Column("longitude", sa.String(length=15), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("building", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_building_latitude"), ["latitude"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_building_longitude"), ["longitude"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_building_number"), ["number"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("building", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_building_number"))
        batch_op.drop_index(batch_op.f("ix_building_longitude"))
        batch_op.drop_index(batch_op.f("ix_building_latitude"))

    op.drop_table("building")
    # ### end Alembic commands ###
