"""changes two fields

Revision ID: 2de816c9ee54
Revises: 7ede255b7202
Create Date: 2023-10-11 23:07:54.621822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de816c9ee54'
down_revision = '7ede255b7202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
