"""chang

Revision ID: f5891dcaa098
Revises: 
Create Date: 2023-10-12 13:50:21.732057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5891dcaa098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_number'), ['number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_number'))
        batch_op.drop_index(batch_op.f('ix_building_longitude'))
        batch_op.drop_index(batch_op.f('ix_building_latitude'))

    op.drop_table('building')
    # ### end Alembic commands ###
